DROP DATABASE IF EXISTS Timden;
CREATE DATABASE IF NOT EXISTS Tindem;

USE Tindem;

DROP TABLE IF EXISTS TblMatch;
DROP TABLE IF EXISTS TblApplicant;
DROP TABLE IF EXISTS TblProfile;
DROP TABLE IF EXISTS TblCity;
DROP TABLE IF EXISTS TblCountry;
DROP TABLE IF EXISTS TblCompany;
DROP TABLE IF EXISTS TblUser;

CREATE TABLE TblUser (
	UseId INT(11) AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE TblCompany(
	NIT INT(11) PRIMARY KEY,
    dayOfFounded DATE NOT NULL
);

CREATE TABLE TblCountry(
	CouId INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE TblCity(
	CitId INT(11) AUTO_INCREMENT PRIMARY KEY,
    CouId INT(11) NOT NULL,
    name VARCHAR(85) NOT NULL,
    CONSTRAINT FKCountry FOREIGN KEY(CouId) REFERENCES TblCountry(CouId) ON DELETE NO ACTION ON UPDATE CASCADE
);

/*La propiedad "interests" cumple los requisitos de ser una tabla*/
CREATE TABLE TblProfile(
	ProId INT(11) AUTO_INCREMENT PRIMARY KEY,
    NIT INT(11) NOT NULL,
    UseId INT(11) NOT NULL,
    CitId INT(11) NOT NULL,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(255) NULL,
    interest INT NOT NULL,
    CONSTRAINT FKCompany FOREIGN KEY(NIT) REFERENCES TblCompany(NIT) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKUser FOREIGN KEY(UseId) REFERENCES TblUser(UseId) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKCity FOREIGN KEY(CitId) REFERENCES TblCity(CitId) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE TblApplicant(
	AppId  INT AUTO_INCREMENT PRIMARY KEY,
    ProId INT(11),
    dateOfBirth DATE NOT NULL,
    CONSTRAINT FKProfile FOREIGN KEY(ProId) REFERENCES TblProfile(ProId) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE TblMatch (
	MatId INT AUTO_INCREMENT PRIMARY KEY,
    AppId  INT(11) NOT NULL,
    NIT INT(11) NOT NULL,
    CONSTRAINT FKApplicant FOREIGN KEY(AppId) REFERENCES TblApplicant(AppId) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKCompany2 FOREIGN KEY(NIT) REFERENCES TblCompany(NIT) ON DELETE NO ACTION ON UPDATE CASCADE
);